version: '3'

services:
    consul:
        image: smebberson/alpine-consul
        environment:
            - CONSUL_BOOTSTRAP_DEBUG=true
            - CONSUL_BOOTSTRAP_EXPECT=1
    consului:
        image: smebberson/alpine-consul-ui
        environment:
            - CONSUL_BOOTSTRAP_DEBUG=true
        ports:
            - 8500:8500
    redis:
        image: smebberson/alpine-consul-redis
        environment:
            - CONSUL_BOOTSTRAP_DEBUG=true
    backend:
        build: .
        image: backend:local
        ports:
            - 5000:5000
        volumes:
            - .:/app
        depends_on:
            - consului
        entrypoint:
            - sh
            - -c
            - './wait-for consului:8600 -- python backend.py'
#            - python
#            - /app/backend.py
    dnsresolver:
        image: ce-server
        volumes:
            - .:/app
        depends_on:
            - consului
        entrypoint:
            - python
            - /app/dns_resolver.py
